#!/bin/bash
# 
#
# Copyright 2019 AT&T Intellectual Property
# Copyright 2019 Nokia
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#


export RMR_SEED_RT=/usr/local/route/local.rt
#export RMR_SEED_RT=$HOME/global_rmr_files/global_rmr_routes.rt
export RMR_RTG_SVC=localhost:9990
#export DUMMY_SENDER_RMR_RCV_PORT=48086
export E2TERM_RMR_RCV_PORT=48886
export DEMO_SENDER_PTO=1
export DEMO_MAX_PAYLOAD_BYTES=240
