/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2AP-Containers"
 * 	found in "e2ap-v01.01.00.asn"
 * 	`asn1c -pdu=auto -fincludes-quoted -fcompound-names -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example`
 */

#ifndef	_ProtocolIE_Container_H_
#define	_ProtocolIE_Container_H_


#include "asn_application.h"

/* Including external dependencies */
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct RICsubscriptionRequest_IEs;
struct RICsubscriptionResponse_IEs;
struct RICsubscriptionFailure_IEs;
struct RICsubscriptionDeleteRequest_IEs;
struct RICsubscriptionDeleteResponse_IEs;
struct RICsubscriptionDeleteFailure_IEs;
struct RICindication_IEs;
struct RICcontrolRequest_IEs;
struct RICcontrolAcknowledge_IEs;
struct RICcontrolFailure_IEs;
struct ErrorIndication_IEs;
struct E2setupRequestIEs;
struct E2setupResponseIEs;
struct E2setupFailureIEs;
struct E2connectionUpdate_IEs;
struct E2connectionUpdateAck_IEs;
struct E2connectionUpdateFailure_IEs;
struct E2nodeConfigurationUpdate_IEs;
struct E2nodeConfigurationUpdateAcknowledge_IEs;
struct E2nodeConfigurationUpdateFailure_IEs;
struct ResetRequestIEs;
struct ResetResponseIEs;
struct RICserviceUpdate_IEs;
struct RICserviceUpdateAcknowledge_IEs;
struct RICserviceUpdateFailure_IEs;
struct RICserviceQuery_IEs;

/* ProtocolIE-Container */
typedef struct ProtocolIE_Container_226P0 {
	A_SEQUENCE_OF(struct RICsubscriptionRequest_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_226P0_t;
typedef struct ProtocolIE_Container_226P1 {
	A_SEQUENCE_OF(struct RICsubscriptionResponse_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_226P1_t;
typedef struct ProtocolIE_Container_226P2 {
	A_SEQUENCE_OF(struct RICsubscriptionFailure_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_226P2_t;
typedef struct ProtocolIE_Container_226P3 {
	A_SEQUENCE_OF(struct RICsubscriptionDeleteRequest_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_226P3_t;
typedef struct ProtocolIE_Container_226P4 {
	A_SEQUENCE_OF(struct RICsubscriptionDeleteResponse_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_226P4_t;
typedef struct ProtocolIE_Container_226P5 {
	A_SEQUENCE_OF(struct RICsubscriptionDeleteFailure_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_226P5_t;
typedef struct ProtocolIE_Container_226P6 {
	A_SEQUENCE_OF(struct RICindication_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_226P6_t;
typedef struct ProtocolIE_Container_226P7 {
	A_SEQUENCE_OF(struct RICcontrolRequest_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_226P7_t;
typedef struct ProtocolIE_Container_226P8 {
	A_SEQUENCE_OF(struct RICcontrolAcknowledge_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_226P8_t;
typedef struct ProtocolIE_Container_226P9 {
	A_SEQUENCE_OF(struct RICcontrolFailure_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_226P9_t;
typedef struct ProtocolIE_Container_226P10 {
	A_SEQUENCE_OF(struct ErrorIndication_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_226P10_t;
typedef struct ProtocolIE_Container_226P11 {
	A_SEQUENCE_OF(struct E2setupRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_226P11_t;
typedef struct ProtocolIE_Container_226P12 {
	A_SEQUENCE_OF(struct E2setupResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_226P12_t;
typedef struct ProtocolIE_Container_226P13 {
	A_SEQUENCE_OF(struct E2setupFailureIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_226P13_t;
typedef struct ProtocolIE_Container_226P14 {
	A_SEQUENCE_OF(struct E2connectionUpdate_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_226P14_t;
typedef struct ProtocolIE_Container_226P15 {
	A_SEQUENCE_OF(struct E2connectionUpdateAck_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_226P15_t;
typedef struct ProtocolIE_Container_226P16 {
	A_SEQUENCE_OF(struct E2connectionUpdateFailure_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_226P16_t;
typedef struct ProtocolIE_Container_226P17 {
	A_SEQUENCE_OF(struct E2nodeConfigurationUpdate_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_226P17_t;
typedef struct ProtocolIE_Container_226P18 {
	A_SEQUENCE_OF(struct E2nodeConfigurationUpdateAcknowledge_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_226P18_t;
typedef struct ProtocolIE_Container_226P19 {
	A_SEQUENCE_OF(struct E2nodeConfigurationUpdateFailure_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_226P19_t;
typedef struct ProtocolIE_Container_226P20 {
	A_SEQUENCE_OF(struct ResetRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_226P20_t;
typedef struct ProtocolIE_Container_226P21 {
	A_SEQUENCE_OF(struct ResetResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_226P21_t;
typedef struct ProtocolIE_Container_226P22 {
	A_SEQUENCE_OF(struct RICserviceUpdate_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_226P22_t;
typedef struct ProtocolIE_Container_226P23 {
	A_SEQUENCE_OF(struct RICserviceUpdateAcknowledge_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_226P23_t;
typedef struct ProtocolIE_Container_226P24 {
	A_SEQUENCE_OF(struct RICserviceUpdateFailure_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_226P24_t;
typedef struct ProtocolIE_Container_226P25 {
	A_SEQUENCE_OF(struct RICserviceQuery_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_226P25_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_226P0;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_226P0_specs_1;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_226P0_1[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_226P0_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_226P1;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_226P1_specs_3;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_226P1_3[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_226P1_constr_3;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_226P2;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_226P2_specs_5;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_226P2_5[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_226P2_constr_5;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_226P3;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_226P3_specs_7;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_226P3_7[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_226P3_constr_7;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_226P4;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_226P4_specs_9;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_226P4_9[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_226P4_constr_9;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_226P5;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_226P5_specs_11;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_226P5_11[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_226P5_constr_11;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_226P6;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_226P6_specs_13;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_226P6_13[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_226P6_constr_13;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_226P7;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_226P7_specs_15;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_226P7_15[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_226P7_constr_15;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_226P8;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_226P8_specs_17;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_226P8_17[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_226P8_constr_17;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_226P9;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_226P9_specs_19;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_226P9_19[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_226P9_constr_19;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_226P10;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_226P10_specs_21;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_226P10_21[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_226P10_constr_21;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_226P11;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_226P11_specs_23;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_226P11_23[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_226P11_constr_23;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_226P12;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_226P12_specs_25;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_226P12_25[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_226P12_constr_25;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_226P13;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_226P13_specs_27;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_226P13_27[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_226P13_constr_27;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_226P14;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_226P14_specs_29;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_226P14_29[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_226P14_constr_29;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_226P15;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_226P15_specs_31;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_226P15_31[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_226P15_constr_31;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_226P16;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_226P16_specs_33;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_226P16_33[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_226P16_constr_33;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_226P17;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_226P17_specs_35;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_226P17_35[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_226P17_constr_35;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_226P18;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_226P18_specs_37;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_226P18_37[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_226P18_constr_37;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_226P19;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_226P19_specs_39;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_226P19_39[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_226P19_constr_39;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_226P20;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_226P20_specs_41;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_226P20_41[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_226P20_constr_41;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_226P21;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_226P21_specs_43;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_226P21_43[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_226P21_constr_43;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_226P22;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_226P22_specs_45;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_226P22_45[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_226P22_constr_45;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_226P23;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_226P23_specs_47;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_226P23_47[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_226P23_constr_47;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_226P24;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_226P24_specs_49;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_226P24_49[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_226P24_constr_49;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_226P25;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_226P25_specs_51;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_226P25_51[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_226P25_constr_51;

#ifdef __cplusplus
}
#endif

#endif	/* _ProtocolIE_Container_H_ */
#include "asn_internal.h"
