# 
#
# Copyright 2019 AT&T Intellectual Property
# Copyright 2019 Nokia
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Docker file to build container for E2 Simulator, for which it can be called
# to run both the E2 Agent and E2 Termination.
# Note: run docker comamnds from root directory of e2sim, e.g., $E2SIM_DIR
#
# build with 2 steps
#   $ sudo docker build -f docker/Dockerfile_base -t e2sim_base .
#   $ sudo docker build -f docker/Dockerfile -t e2sim .
#
# run e2 termination
#   $ sudo docker run --rm --net host -it e2sim sh -c "./build/e2sim 127.0.0.2"

FROM ubuntu:16.04


# location in the container
ENV E2SIM_DIR /home/e2sim

# Install necessary packages
RUN apt-get update \
	&& apt-get install -y \
	build-essential \
	git \
	cmake \
	libsctp-dev \
	lksctp-tools \
	autoconf \
	automake \
	libtool \
	bison \
	flex

# For rmr
RUN apt-get install -y bash vim ksh iputils-ping
RUN apt-get clean

# Copy E2Sim to the container
COPY	 	./ ${E2SIM_DIR}
WORKDIR ${E2SIM_DIR}
RUN	    ./docker/install_asn1c

#-------------INSTALL rmr ------------------------
RUN ./docker/install_rmr
