/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-KPM-RC"
 * 	found in "e2sm-kpm-rc.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -gen-PER -D .`
 */

#ifndef	_E2SM_KPM_EventTriggerDefinition_Format1_H_
#define	_E2SM_KPM_EventTriggerDefinition_Format1_H_


#include "asn_application.h"

/* Including external dependencies */
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Trigger_ConditionIE_Item;

/* E2SM-KPM-EventTriggerDefinition-Format1 */
typedef struct E2SM_KPM_EventTriggerDefinition_Format1 {
	struct E2SM_KPM_EventTriggerDefinition_Format1__policyTest_List {
		A_SEQUENCE_OF(struct Trigger_ConditionIE_Item) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *policyTest_List;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} E2SM_KPM_EventTriggerDefinition_Format1_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_E2SM_KPM_EventTriggerDefinition_Format1;

#ifdef __cplusplus
}
#endif

#endif	/* _E2SM_KPM_EventTriggerDefinition_Format1_H_ */
#include "asn_internal.h"
