/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2AP-PDU-Contents"
 * 	found in "e2ap-v01.01.00.asn"
 * 	`asn1c -pdu=auto -fincludes-quoted -fcompound-names -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example`
 */

#ifndef	_E2nodeComponentConfigUpdateAck_Item_H_
#define	_E2nodeComponentConfigUpdateAck_Item_H_


#include "asn_application.h"

/* Including external dependencies */
#include "E2nodeComponentType.h"
#include "E2nodeComponentConfigUpdateAck.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct E2nodeComponentID;

/* E2nodeComponentConfigUpdateAck-Item */
typedef struct E2nodeComponentConfigUpdateAck_Item {
	E2nodeComponentType_t	 e2nodeComponentType;
	struct E2nodeComponentID	*e2nodeComponentID;	/* OPTIONAL */
	E2nodeComponentConfigUpdateAck_t	 e2nodeComponentConfigUpdateAck;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} E2nodeComponentConfigUpdateAck_Item_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_E2nodeComponentConfigUpdateAck_Item;
extern asn_SEQUENCE_specifics_t asn_SPC_E2nodeComponentConfigUpdateAck_Item_specs_1;
extern asn_TYPE_member_t asn_MBR_E2nodeComponentConfigUpdateAck_Item_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _E2nodeComponentConfigUpdateAck_Item_H_ */
#include "asn_internal.h"
